export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  PRIMARY_COLOR: '#7695FF', //blue
  PRIMARY_COLOR_2: '#FFE356', //yello
  PRIMARY_COLOR_3: '#FF7D71', //red
  SECONDARY_COLOR: '#FFF7EA', //beige
  SECONDARY_COLOR_2: '#BDCCFF', //beige
  FONT_WEIGHT_LIGHT: 200,
  FONT_WEIGHT_MEDIUM: 600,
  FONT_WEIGHT_HEAVY: 800
};